/* getobj.c
 *
 * by Kelley Nielsen, for use with xtrascreenhacks
 * 
 * utility to read a .obj file generated by blender
 * and output the list of vertices, normals, etc
 * into a .c and companion .h file that can be fed to opengl.
 * 
 * Handles only files that have only one object,
 * doesn't handle material properties,
 * depends on vertices, normals, etc being grouped together
 * names of arrays and generated file depend on the base name of the obj file
 */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>

/* counts occurences of a certain character in a string */
int strchrct(const char *s, const char c)
{
  int count = 0;
  int length;
  int itor;

  length = strlen(s);
  for (itor = 0; itor < length; itor++)
    {
      if (s[itor] == c) count++;
    }
  return count;
}

int main(int argc, char *argv[])
{
  char * basename;
  char vname[128];
  char vtname[128];
  char vnname[128];
  FILE * objfile;
  char inputline[128];
  int facevcount;
  char * inputtoken;
  char delims[] = " ";
  char state[2];
  double outputval;
  int numverts = 0, numtexcoords = 0, numnorms = 0, numfaces = 0;
  fpos_t startfaces;
  bool saveposition = false;
  int itor;

  if (argc < 2)
    {
      printf("Usage: getobj <filename>\n");
      return;
    }

  if ((objfile = fopen(argv[1], "r")) == (FILE *)NULL)
  {
    fprintf(stderr, "Cannot open file %s, exiting\n", argv[1]);
    return;
  }

  /* it would be better to malloc the needed space */
  basename = strtok(strrchr(argv[1], '/') + 1, ".");
  if (strlen(basename) > 119)
    {
      fprintf(stderr, "Name of object is too long, exiting\n");
      return;
    }
/*   printf("%s\n", argv[1]); */
/*   if (strcmp (argv[1] + 1, "obj") != 0) */
/*     { */
/*       fprintf(stderr, "Not an OBJ file, exiting\n"); */
/*       return; */
/*     } */
/*   strcpy (vname, basename); strcat (vname, "Vertices"); */
/*   strcpy (vtname, basename); strcat (vtname, "Texcoords"); */
/*   strcpy (vnname, basename); strcat (vnname, "Normals"); */

  strcpy(state, "st");
  while(fgets(inputline, 255, objfile)!=NULL)
  {
   facevcount = strchrct(inputline, ' ');
      inputtoken = strtok(inputline, delims);

      if(strcmp(inputtoken, "v") == 0)
	{
	  if (strcmp(state, "v") != 0)
	    {
	      memset(state, 0, 2);
	      strcpy(state, "v");
	      printf("GLfloat %sVertices[][3] = {\n", basename);
	    }
	  if (numverts != 0) printf(",\n");
	  printf("  {");
          for (itor = 0; itor < 3; itor++)
	    {
             inputtoken = strtok(NULL, delims);
	     /* conversion gets rid of extraneous newlines */
             outputval = atof(inputtoken);
             printf("%f", outputval); 
	     if (itor < 2) printf(", ");
            }
	  printf("}");
          numverts++;  
        }  /* vertices case */

      /* texcoords case goes here, is similar to normals case */


      if(strcmp(inputtoken, "vn") == 0)
	{
	  if (strcmp(state, "vn") != 0)
	    {
	      memset(state, 0, 2);
	      strcpy(state, "vn");
	      printf("};\n\nGLfloat %sNormals[][3] = {\n", basename);
	    }
	  if (numnorms != 0) printf(",\n");
	  printf("  {");
          for (itor = 0; itor < 3; itor++)
	    {
             inputtoken = strtok(NULL, delims);
	     /* conversion gets rid of extraneous newlines */
             outputval = atof(inputtoken);
             printf("%f", outputval); 
	     if (itor < 2) printf(", ");
            }
	  printf("}");
          numnorms++;  
        }  /* normals case */

      if (strcmp(inputtoken, "f") == 0)
	{
	  if (strcmp(state, "f") != 0)
	    {
	      memset(state, 0, 2);
	      strcpy(state, "f");
	      printf("};\n\n");
	      saveposition = true;
	    }
	  if (facevcount == 3) numfaces++;

	}  /* faces case -- first (triangles) pass */
    if (saveposition == false) fgetpos(objfile, &startfaces);

  } /* first loop over lines in the input file */

  fsetpos(objfile, &startfaces);
  while(fgets(inputline, 255, objfile)!=NULL)
    {
      facevcount = strchrct(inputline, ' ');
      inputtoken = strtok(inputline, delims);
      if (strcmp(inputtoken, "f") == 0)
	{
	  if (facevcount == 4) numfaces++;
	}
    } /* second loop over last of input file == faces case, triangles pass */
  
  fclose(objfile);
    printf("\nMembers found: %d vertices, %d texture coordinates, %d normals, %d faces\n", numverts, numtexcoords, numnorms, numfaces);

  return 0;
}

/* faces go: vertex/texcoord/normal, or vertex//normal (or vertex/texcoord )
 * remember that indexing starts at 1, not 0
 *
 * http://en.wikipedia.org/wiki/Obj
 */

/* for generated c program,
 * make call to render object like this: bevelcube() or bevelcube(1.0)
 * this function just calls a display list (?? teapot doesn't)
 */ 


/* put in -h (help) */

/* test for valid obj--segfaults on c file */

