/* getobj.c
 *
 * by Kelley Nielsen, for use with xtrascreenhacks
 * 
 * utility to read a .obj file generated by blender
 * and output the list of vertices, normals, etc
 * into a .c and companion .h file that can be fed to opengl.
 * 
 * Handles only files that have only one object,
 * doesn't handle material properties,
 * depends on vertices, normals, etc being grouped together
 * names of arrays and generated file depend on the base name of the obj file
 *
 * not yet complete--doesn't handle texcoords, for instance
 */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdbool.h>


/* counts occurences of a certain character in a string */
int strchrct(const char *s, const char c)
{
  int count = 0;
  int length;
  int itor;

  length = strlen(s);
  for (itor = 0; itor < length; itor++)
    {
      if (s[itor] == c) count++;
    }
  return count;
}

void print_preamble(FILE * pfile, char * funcname)
{
  /* put in something about generated with obj2c, etc */
  fprintf(pfile, "/* %s.c\n * generated wtih obj2.c from %s.obj\n */\n\n",
	 funcname, funcname);
  fprintf(pfile, "#include \"%s.h\"\n\n", funcname);

  fprintf(pfile, "void draw%s(void)\n{\n", funcname);
}

void print_hfile( char * funcname )
{
  char hfilename[128];
  char ufuncname[128];
  FILE * hfile;
  int length, itor;

  memset(hfilename, 0, 128);
  strcpy(hfilename, funcname); strcat(hfilename, ".h");
  if ((hfile = fopen(hfilename, "w")) == (FILE *)NULL)
  {
    fprintf(stderr, "Cannot create file %s, printing to stdout\n", hfilename);
    hfile = stdout;
  }
  length = strlen(funcname);
  memset(ufuncname, 0, 128);
  for (itor = 0; itor < length; itor++)
    {
      ufuncname[itor] = toupper(funcname[itor]);
    }
  fprintf(hfile, "/* %s\n * generated wtih obj2.c from %s.obj\n */\n\n",
	 hfilename, funcname);
  fprintf(hfile, "#ifndef _%s_H_\n#define _%s_H_\n\n",
	  ufuncname, ufuncname);
  fprintf(hfile, "#include <GL/gl.h>\n\n");
  fprintf(hfile, "void draw%s(void);\n", funcname);
  fprintf(hfile, "\n#endif\n");
  fclose(hfile);

}

int main(int argc, char *argv[])
{
  char * basename;
  char vname[128];
  char vtname[128];
  char vnname[128];
  char cfilename[128];
  FILE * objfile, * cfile;
  char inputline[128];
  int facevcount;
  char *inputtoken, *inputtokenjr;
  char *inputtokenptr, *inputtokenjrptr;
  char delims[] = " ";  /* probably unneeded--just use literal as elsewhere */
  char state[2]; /* probably unneeded--use counts */
  double outputval;
  int vindex, vtindex, vnindex;
  int numverts = 0, numtexcoords = 0, numnorms = 0, numfaces = 0;
  fpos_t startfaces;
  bool saveposition = false;
  int itor;

  if (argc < 2)
    {
      printf("Usage: getobj <filename>\n");
      return;
    }

  if ((objfile = fopen(argv[1], "r")) == (FILE *)NULL)
  {
    fprintf(stderr, "Cannot open file %s, exiting\n", argv[1]);
    return;
  }

  if (strpbrk(argv[1], "/") == NULL) basename = strtok(argv[1] + 1, ".");
  else basename = strtok(strrchr(argv[1], '/') + 1, ".");
  if (strlen(basename) > 119)
    {
      fprintf(stderr, "Name of object is too long, exiting\n");
      return;
    }
  /* checks if extension is .obj, but not for a valid file */
  inputtoken = strtok(NULL, ".");
  if (strcmp (inputtoken, "obj") != 0)
    {
      fprintf(stderr, "Not an OBJ file, exiting\n");
      return;
    }

  /* it would be better to malloc the needed space for all these names*/
  memset(vname, 0, 128);
  memset(vtname, 0, 128);
  memset(vnname, 0, 128);
  memset(cfilename, 0, 128);
  strcpy (vname, basename); strcat (vname, "Vertices");
  strcpy (vtname, basename); strcat (vtname, "Texcoords");
  strcpy (vnname, basename); strcat (vnname, "Normals");
  strcpy (cfilename, basename); strcat (cfilename, ".c");

  print_hfile(basename);
  if ((cfile = fopen(cfilename, "w")) == (FILE *)NULL)
  {
    fprintf(stderr, "Cannot create file %s, printing to stdout\n", cfilename);
    cfile = stdout;
  }

  print_preamble(cfile, basename);
  strcpy(state, "st");
  while(fgets(inputline, 255, objfile)!=NULL)
  {
   facevcount = strchrct(inputline, ' ');
   inputtoken = strtok_r(inputline, delims, &inputtokenptr);

      if(strcmp(inputtoken, "v") == 0)
	{
	  if (strcmp(state, "v") != 0)
	    {
	      memset(state, 0, 2);
	      strcpy(state, "v");
	      fprintf(cfile, "GLfloat %s[][3] = {\n", vname);
	    }
	  if (numverts != 0) fprintf(cfile, ",\n");
	  fprintf(cfile, "  {");
          for (itor = 0; itor < 3; itor++)
	    {
	      inputtoken = strtok_r(NULL, delims, &inputtokenptr);
	     /* conversion gets rid of extraneous newlines */
             outputval = atof(inputtoken);
             fprintf(cfile, "%f", outputval); 
	     if (itor < 2) fprintf(cfile, ", ");
            }
	  fprintf(cfile, "}");
          numverts++;  
        }  /* vertices case */

      /* texcoords case goes here, is similar to normals case */


      if(strcmp(inputtoken, "vn") == 0)
	{
	  if (strcmp(state, "vn") != 0)
	    {
	      memset(state, 0, 2);
	      strcpy(state, "vn");
	      fprintf(cfile, "};\n\nGLfloat %s[][3] = {\n", vnname);
	    }
	  if (numnorms != 0) fprintf(cfile, ",\n");
	  fprintf(cfile, "  {");
          for (itor = 0; itor < 3; itor++)
	    {
	      inputtoken = strtok_r(NULL, delims, &inputtokenptr);
	     /* conversion gets rid of extraneous newlines */
             outputval = atof(inputtoken);
             fprintf(cfile, "%f", outputval); 
	     if (itor < 2) fprintf(cfile, ", ");
            }
	  fprintf(cfile, "}");
          numnorms++;  
        }  /* normals case */

      if (strcmp(inputtoken, "f") == 0)
	{
	  if (strcmp(state, "f") != 0)
	    {
	      memset(state, 0, 2);
	      strcpy(state, "f");
	      fprintf(cfile, "};\n\n");
	      fprintf(cfile, "  glBegin(GL_QUADS);\n");
	      saveposition = true;
	    }
	  if (facevcount == 4)
	    {
	      for(itor = 0; itor < 4; itor++)
		{
		  inputtoken = strtok_r(NULL, delims, &inputtokenptr);
		  vindex = atoi(strtok_r(inputtoken, "/", &inputtokenjrptr))-1;
/* 		  vtindex = strtok_r(NULL, "/", &inputtokenjrptr); */
		  vnindex = atoi(strtok_r(NULL, "/", &inputtokenjrptr)) - 1;

		  fprintf(cfile, "  glNormal3fv(%s[%d]); glVertex3fv(%s[%d]);\n",
			 vnname, vnindex, vname, vindex);
		}

	      numfaces++;
	    }

	}  /* faces case -- first (quads) pass */
    if (saveposition == false) fgetpos(objfile, &startfaces);

  } /* first loop over lines in the input file */


  fprintf(cfile, "  glEnd();\n\n");
  fprintf(cfile, "  glBegin(GL_TRIANGLES);\n");
  fsetpos(objfile, &startfaces);
  while(fgets(inputline, 255, objfile)!=NULL)
    {
      facevcount = strchrct(inputline, ' ');
      inputtoken = strtok_r(inputline, delims, &inputtokenptr);
      if (strcmp(inputtoken, "f") == 0)
	{
	  if (facevcount == 3)
         {
 	      for(itor = 0; itor < 3; itor++)
		{
		  inputtoken = strtok_r(NULL, delims, &inputtokenptr);
		  vindex = atoi(strtok_r(inputtoken, "/", &inputtokenjrptr))-1;
/* 		   = strtok_r(NULL, "/", &inputtokenjrptr); */
		  vnindex = atoi(strtok_r(NULL, "/", &inputtokenjrptr)) - 1;

		  fprintf(cfile, "  glNormal3fv(%s[%d]); glVertex3fv(%s[%d]);\n",
			 vnname, vnindex, vname, vindex);
		}

          numfaces++;
          }
	}
    } /* second loop over last of input file == faces case, triangles pass */
  fprintf(cfile, "  glEnd();\n}\n");
  
  fclose(objfile);
  fclose(cfile);
    printf("\nMembers found: %d vertices, %d texture coordinates, %d normals, %d faces\n", numverts, numtexcoords, numnorms, numfaces);

  return 0;
}

/* faces go: vertex/texcoord/normal, or vertex//normal (or vertex/texcoord )
 * remember that indexing starts at 1, not 0
 *
 * http://en.wikipedia.org/wiki/Obj
 */

/* for generated c program,
 * make call to render object like this: bevelcube() or bevelcube(1.0)
 * this function just calls a display list (?? teapot doesn't)
 */ 

/* strtok_r doesn't return empty string -- fix
 * if two delimiters occur next to each other, no token is seen between them
 *
 * will probably need to count slashes before processing
 * for now, program assumes vertex//normal faces
 */


/* put in -h (help) */


/* there is a lot of reduncancy in generated drawing calls
 * eventually, test for face normals, triangle fans/strips, etc
 * will require caching and parsing of vertices
 * also, generates an empty glBegin/end pair if mesh is all quads/triangles
 */

